CREATE DATABASE PIZZAHUT;
USE PIZZAHUT;
SELECT * FROM PIZZAS;
# WE HAVE IMPORTED 2 TABLES FOR 3RD ONE WE ARE CREATING A TABLE

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
ORDER_DATE DATE NOT NULL,
ORDER_TIME TIME NOT NULL
);

# NOW WE ARE IMPORTING THE DATA IN THE ORDERS TABLE BECAUSE THE FORMAT OF TABLE THAT WE HAVE WANTED WAS NOT PRESENT THERE

SELECT * FROM ORDERS;

# AGAIN CREATING NEW TABLE THEN IMPORTING THE DATA IN IT

CREATE TABLE ORDER_DETAILS(
ORDER_DETAILS_ID INT PRIMARY KEY,
ORDER_ID INT NOT NULL,
PIZZA_ID TEXT NOT NULL,
QUANTITY INT NOT NULL
);

SELECT * FROM ORDER_DETAILS;

# LET'S START WITH THE QUESTIONS

-- RETRIEVE THE TOTAL NO.S OF ORDERS PLACED

SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;

-- Calculate the total revenue generated from pizza sales.

SELECT * FROM ORDER_DETAILS;

SELECT * FROM PIZZAS;

SELECT ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),2) AS TOTAL_SALES 
FROM ORDER_DETAILS 
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID ;

-- Identify the highest-priced pizza.
SELECT * FROM PIZZA_TYPES;
SELECT * FROM PIZZAS;

SELECT PIZZA_TYPES.NAME , PIZZAS.PRICE FROM PIZZA_TYPES
JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
ORDER BY PIZZAS.PRICE DESC LIMIT 1;

-- Identify the most common pizza size ordered.

SELECT * FROM PIZZAS;
SELECT * FROM ORDER_DETAILS;

SELECT PIZZAS.SIZE, SUM(ORDER_DETAILS.QUANTITY) AS TOTAL_PIZZAS FROM PIZZAS
JOIN ORDER_DETAILS
ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY PIZZAS.SIZE 
ORDER BY TOTAL_PIZZAS DESC;

-- List the top 5 most ordered pizza types along with their quantities.

select * from order_details;
select * from pizza_types;
select * from pizzas;

SELECT PIZZA_TYPES.NAME AS PIZZA_NAME , SUM(ORDER_DETAILS.QUANTITY) AS TOTAL_QTY_ORDERED
FROM ORDER_DETAILS
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN PIZZA_TYPES 
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QTY_ORDERED DESC LIMIT 5;

-- Join the necessary tables to find the total quantity of each pizza category ordered.

SELECT * FROM PIZZA_TYPES;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM PIZZAS;

SELECT PIZZA_TYPES.CATEGORY AS CATEGORY,SUM(ORDER_DETAILS.QUANTITY) AS QTY_ORDERED
FROM ORDER_DETAILS
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN PIZZA_TYPES
ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
GROUP BY CATEGORY
ORDER BY QTY_ORDERED ;

-- Determine the distribution of orders by hour of the day.

SELECT * FROM ORDERS;

SELECT HOUR(ORDER_TIME) AS HOUR , COUNT(ORDER_ID) AS ORDER_COUNT
FROM ORDERS
GROUP BY HOUR 
ORDER BY ORDER_COUNT DESC;

-- Join relevant tables to find the category-wise distribution of pizzas.

SELECT * FROM PIZZA_TYPES;

SELECT CATEGORY,COUNT(NAME) FROM PIZZA_TYPES
GROUP BY CATEGORY;

-- Group the orders by date and calculate the average number of pizzas ordered per day.

SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;

SELECT ROUND(AVG(PIZZA_ORDERED),0) as AVG_PIZZA_ORDERED_PER_DAY FROM 
(SELECT ORDERS.ORDER_DATE AS DATE,SUM(ORDER_DETAILS.QUANTITY) AS PIZZA_ORDERED
FROM ORDERS
JOIN ORDER_DETAILS
ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
GROUP BY DATE) AS QUANTITY_ORDERED_PER_DAY ;

-- Determine the top 3 most ordered pizza types based on revenue.

SELECT PIZZA_TYPES.NAME AS PIZZA_NAME, SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
FROM ORDER_DETAILS
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN PIZZA_TYPES
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY PIZZA_NAME 
ORDER BY REVENUE DESC LIMIT 3 ;

-- Calculate the percentage contribution of each pizza type to total revenue.

# USING WINDOW FUNCTION
SELECT PIZZA_TYPES.CATEGORY AS CATEGORY, ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE)*100/SUM(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE)) 
OVER() ,2) AS PERCENTAGE_CONTRIBUTED
FROM ORDER_DETAILS
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN PIZZA_TYPES
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY CATEGORY ;

# USING SUB QUERY

SELECT PIZZA_TYPES.CATEGORY AS CATEGORY , ROUND(SUM(ORDER_DETAILS.QUANTITY*PIZZAS.PRICE)*100/ (SELECT SUM(ORDER_DETAILS.QUANTITY*PIZZAS.PRICE) FROM ORDER_DETAILS
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID),2)
FROM ORDER_DETAILS
JOIN PIZZAS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN PIZZA_TYPES
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
GROUP BY CATEGORY ;

-- Analyze the cumulative revenue generated over time.

SELECT ORDER_DATE, SUM(REVENUE) OVER(ORDER BY ORDER_DATE) AS CUM_REVENUE
FROM 
(SELECT O.ORDER_DATE AS ORDER_DATE,SUM(OD.QUANTITY * P.PRICE) AS REVENUE
FROM ORDERS AS O
JOIN ORDER_DETAILS AS OD
ON O.ORDER_ID = OD.ORDER_ID
JOIN PIZZAS AS P
ON OD.PIZZA_ID = P.PIZZA_ID
GROUP BY ORDER_DATE) AS SALES ;

-- Determine the top 3 most ordered pizza types based on revenue for each pizza category.
SELECT CATEGORY,NAME,REVENUE 
FROM
(SELECT CATEGORY,NAME,REVENUE, RANK() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS R
FROM
(SELECT PT.CATEGORY,PT.NAME, SUM(OD.QUANTITY*P.PRICE) AS REVENUE
FROM ORDER_DETAILS AS OD
JOIN PIZZAS AS P
ON OD.PIZZA_ID = P.PIZZA_ID
JOIN PIZZA_TYPES AS PT
ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
GROUP BY CATEGORY , NAME ) AS A) AS B
WHERE R<=3;

-- Here are some of the key insights I discovered:

# 📊 Overall Performance
-- • Total Orders: 21,350
-- • Total Revenue: 817,860
-- • Average Pizza Orders per Day: 138

# 🍕 Product Insights
-- • Highest-priced pizza: Greek Pizza – 35.95
-- • Most ordered pizza size: Large (L)
-- • Least ordered size: Double XXL

# 🏆 Top 5 Most Ordered Pizzas

-- Classic Deluxe
-- Barbecue Chicken
-- Hawaiian Pizza
-- Pepperoni Pizza
-- Thai Chicken Pizza

# 💰 Top 3 Pizzas by Revenue

-- Thai Chicken Pizza
-- Barbecue Chicken Pizza
-- California Chicken Pizza

# 📈 Category Insights
-- • Most ordered category: Classic
-- • Least ordered category: Chicken
-- • Classic contributed the highest share of total revenue: 26.91%
-- • Chicken contributed the lowest share: 23.96%

# ⏰ Peak Ordering Hours
-- The highest order volumes were observed around 12 PM, 1 PM, 5 PM, 6 PM, and 7 PM, after which orders started to decline.
